### PR TITLE
Issue #263 - Request the removal of Geoman (Leaflet Plugin For Creati…

### PR DESCRIPTION
**Pull request by ksalamy**
Request the removal of Geoman (Leaflet Plugin For Creating And Editing Geometry Layers) from Home Map.

Geoman is not needed. Removing it from the SMDB UI code base.

### CODE REVIEW

**Comment by ksalamy** [comment]
Please review and merge this edit. -K

**Comment by ksalamy** [comment]
Also, adding new commit for #261 (Content of detail views hidden behind page header #261). Please review and commit into main.

**Review by MBARIMike — COMMENTED** [review]
I'm curious about the new CSS IDs added to filters.css.  Are they necessary for the removal of Geoman?

**Review by MBARIMike — COMMENTED** [review]
Oh, I see now that the .css changes made are in relation to https://github.com/mbari-org/SeafloorMappingDB/issues/261.

I still see the image in the detail page for Compilations hidden behind the page header.

Screenshot 2024-10-28 at 11 16 16 AM

**Review by MBARIMike — COMMENTED** [review]
Rather than continuing to add css attributes I wonder if it might be better to remove ones leading to a more minimal design that's easier to maintain.

**Review by MBARIMike — COMMENTED** [review]
The Expeditions detail page is somewhat improved with this PR. Before the entire title was hidden by the page header:
Screenshot 2024-10-28 at 11 40 57 AM

In this PR, the title is visible, but is quite narrow:
Screenshot 2024-10-28 at 11 42 19 AM

**Comment by ksalamy** [comment]
Mike, 

The pull request for Geoman removal was sent 4 months ago. No, major changes to the css were not required that update. 

However, I recently made changes to the view of various pages to resolve several reported issues, some including the view 
of your Crispy Forms, so that css works with all. This involved updating the filter.css. 

These updates were detailed as another change (by issue #261) within the original pull request. The css changes I have made 
are needed so that specific page-based requests do not affect the entire UI. Please review and merge these pull requests. 

Karen 
_______________ 
Karen A. Salamy 
Associate SW Engineer, MBARI 
P 831.775.1820 , F 831.775.1620 

	
	
Monterey Bay Aquarium Research Institute (MBARI) 
7700 Sandholdt Road, Moss Landing CA 95039 
[ http://www.mbari.org/ | www.mbari.org ] 
Advancing marine science and engineering to understand our changing ocean. 



"If we knew what it was we were doing, it would not be called research, would it?" - Albert Einstein (1879-1955) 

P Please consider the environment before printing this e-mail.

**Comment by MBARIMike** [comment]
Okay. I will merge this PR and pull to production, but there are still issues with detail page rendering.

**Comment by ksalamy** [comment]
Hi Mike, 

I know there are still some issues with pages rendering. You stated you wanted me to do 
small incremental changes instead of larger updates all at once. 

I will have more pull requests this week. 

Karen 
_______________ 
Karen A. Salamy 
Associate SW Engineer, MBARI 
P 831.775.1820 , F 831.775.1620 

	
	
Monterey Bay Aquarium Research Institute (MBARI) 
7700 Sandholdt Road, Moss Landing CA 95039 
[ http://www.mbari.org/ | www.mbari.org ] 
Advancing marine science and engineering to understand our changing ocean. 



"If we knew what it was we were doing, it would not be called research, would it?" - Albert Einstein (1879-1955) 

P Please consider the environment before printing this e-mail.

**Comment by MBARIMike** [comment]
This PR has been pulled to production.

**Pull request merged**
