### PR TITLE
Adding current image, favicon and Oceans Basemap Layer to SMDB.

### PR DESCRIPTION
**Pull request by ksalamy**
This is my first pass at committing changes to the SMDB code.  I have added the current favicon, logo and ESRI World Oceans basemap Layer in this commit.  I still need to add Oceans:labels though.

### CODE REVIEW

**Comment by MBARIMike** [comment]
There are some conflicts as noted by the comment above. These might be resolved by fetching from upstream in your repository so that your code is synchronized with where it needs to be merged. I think you can do this on the web site by clicking on the "Fetch upstream" link in your repo: https://github.com/ksalamy/SeafloorMappingDB.

**Comment by ksalamy** [comment]
Ok. I have fixed the conflicts from the merge. - Karen

**Review by MBARIMike — CHANGES_REQUESTED** [review]
Sweet!

This is what I get with this PR on my development system:
Screen Shot 2021-12-03 at 4 48 50 PM

I did have to change the URL for the image in base.html:
```diff
➜  SeafloorMappingDB git:(new-logo) ✗ git diff smdb/smdb/templates/base.html
diff --git a/smdb/smdb/templates/base.html b/smdb/smdb/templates/base.html
index 8c5fcdd..124b704 100644
--- a/smdb/smdb/templates/base.html
+++ b/smdb/smdb/templates/base.html
@@ -54,7 +54,7 @@
           </button>

           <!--<a class="navbar-brand" href="{% url 'home' %}">SeafloorMappingDB</a> -->
-          <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'images/favicons/SMDB_logo_mask2_test1.png' %}" alt="SMDB">
+          <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'images/SMDB_logo_mask2_test1.png' %}" alt="SMDB">
           </a>

           <div class="collapse navbar-collapse" id="navbarSupportedContent">
```

If this is the correct URL for the image then please commit and push that change.

**Comment by ksalamy** [comment]
Hi Mike,

Ok, I *think* I have correctly fixed the link and requested another pull request to reflect that.  The update was only regarding the link in base.html.  Please let me know if I did anything in error.

Thanks!

Karen

**Comment by MBARIMike** [comment]
Hi Karen,

Did you commit and push your change?

-Mike

**Review by MBARIMike — APPROVED** [review]

**Review by MBARIMike — APPROVED** [review]

**Pull request merged**
